### PR TITLE
Fix Bug 1180173

### PR DESCRIPTION
**Pull request by KaratekHD**
This should fix https://bugzilla.opensuse.org/show_bug.cgi?id=1180173

### CODE REVIEW

**Comment by jreidinger** [comment]
@ancorgs can you check this PR? I think original intention is to allow run of journal also without root permissions for user available journal, but maybe it is not so much useful as desktop entry?

**Comment by imobachgs** [comment]
I would say that running the module as a regular user is a valid use case. But let's see if @ancorgs has a different opinion. Perhaps we could have a separate desktop entry for running the module as root (not sure whether it makes sense at all).

**Comment by ancorgs** [comment]
Well, in theory:

- Normal users can see their own entries
- Users in the `systemd-journal` group can see all entries
- Root can also, of course, see all entries

So there are real use cases for running this module without being root. There is even some support to explain the situation if the module is executed with restricted permissions. See https://github.com/yast/yast-journal/pull/41 (I would have worded it the warning a bit different, but it's there).

If the module is showing the "this module must be run as root" instead of displaying the warning about the system messages, then that's indeed a bug. But forcing it to be executed as root is, IMO, not the solution.

**Comment by imobachgs** [comment]
OK, I have closed the [associated bug](https://bugzilla.suse.com/show_bug.cgi?id=1180173).

**Pull request closed without merging**
