### PR TITLE
Usability improvements and updated changelog.

### PR DESCRIPTION
**Pull request by ancorgs**

### CODE REVIEW

**Comment by jreidinger** [comment]
so if I get it filters widgets are always enabled and when you change it, then it is selected?

**Comment by ancorgs** [comment]
The only change is that the checkbox is automagically checked if you change the value of the text field. This would be the initial screen:
```
[  ] For these systemd units: [.....]
[  ] With at least this priority: [emerg↓]
```
Sometimes I change the value but forget to actually activate the filter, like this:
```
[  ] For these systemd units: [i wrote something here]
[  ] With at least this priority: [debug↓]
```
Which makes not effect. Now as soon as I write something in the text box or change the combobox, y get this without needing extra clicks:
```
[X] For these systemd units: [i wrote something here]
[X] With at least this priority: [debug↓]
```
I assume users changing a value actually want it to matter.

**Comment by ancorgs** [comment]
Mmmm, I should do the same for the time selectors to be consistent

**Comment by lslezak** [comment]
The changelog contains `Some cleanup in the strings for better internationalization` and ` Updated to use the latest version of the YaST libraries`, but I cannot see anything like that... :question:

**Comment by ancorgs** [comment]
@lslezak that was actually made during the cleaning-up commits but never reflected in the changelog.

**Comment by jreidinger** [comment]
travis failed

**Comment by jreidinger** [comment]
LGTM if travis passed

**Pull request merged**
